### PR TITLE
Update aws nuke

### PR DESCRIPTION
**Pull request by dilip0515**
- [x] updating the aws nuke version  which is out of date with  https://github.com/rebuy-de/aws-nuke

### CODE REVIEW

**Review by robertcrockett — DISMISSED** [review]
Looks good to me! I am assuming you will manage the conflicts.

**Comment by dilip0515** [comment]
@robertcrockett Yes will take care of the conflicts before merging it

**Comment by dilip0515** [comment]
> @robertcrockett Yes will take care of the conflicts before merging it

@robertcrockett i have resolved the conflicts and pushed the code can you review the PR

**Review by robertcrockett — CHANGES_REQUESTED** [review]
It looks like there is a redeclaration of  logrus in the resources/iam-role-policy.go. There is also a statement that this imported, but not used.

There are several other errors in the test.project CI that are failing as well. A couple of undefined variables:
f.logGroupName undefined
targetGroupARNToRsc undefined.

Can these be updated so the test project successfully runs?

**Pull request closed without merging**
